### PR TITLE
fix/Add test case and parameter validation

### PR DESCRIPTION
**Pull request by ergjustin**
27 test case added and argument validation in common.js

### CODE REVIEW

**Comment by jscottsf** [comment]
Approving. We should eventually get realistic input datasets from Dendra. e.g. `geo: { type: 'Point', coordinates: ['32.9029', '-96.5639', '4'] },` the coordinates are not strings. Will need to review these test cases over time.

**Review by jscottsf — APPROVED** [review]
Approving. We should eventually get realistic input datasets from Dendra. e.g. geo: { type: 'Point', coordinates: ['32.9029', '-96.5639', '4'] }, the coordinates are not strings. Will need to review these test cases over time.

**Comment by jscottsf** [comment]
@ergjustin Seems one test case is failing in the pipeline.

**Review by jscottsf — COMMENTED** [review]
Thinking we should check for truthy since null is an object and will fail the validation check if null is passed.

So refactor to something like:

```
if (!(xyz && typeof xyz === 'object')) return ''
```

**Comment by ergjustin** [comment]
Added object validation ```if (!(xyz && typeof xyz === 'object')) return ''```
Changed toLocaleString to toISOString
Remove `queryInfoType` test case because, In queryInfoType function use `new Date().toISOString()`  some time may occur an error on time value

**Pull request merged**
